# Generated by Django 5.0.6 on 2026-03-25 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_cancha'),
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticajugador',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estadisticas_torneo', to='inscripciones.equipo'),
        ),
    ]
