# Generated by Django 5.0.6 on 2026-03-30 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_cancha'),
        ('torneos', '0002_estadisticajugador_equipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['fase', 'jornada', 'fecha'], 'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AddField(
            model_name='partido',
            name='fase',
            field=models.CharField(choices=[('GRUPOS', 'Fase de grupos'), ('CUARTOS', 'Cuartos de final'), ('SEMIFINAL', 'Semifinal'), ('TERCER_PUES', 'Tercer puesto'), ('FINAL', 'Final')], default='GRUPOS', max_length=15),
        ),
        migrations.AddField(
            model_name='torneo',
            name='fase_actual',
            field=models.CharField(blank=True, choices=[('GRUPOS', 'Fase de grupos'), ('CUARTOS', 'Cuartos de final'), ('SEMIFINAL', 'Semifinal'), ('TERCER_PUES', 'Tercer puesto'), ('FINAL', 'Final')], default='GRUPOS', max_length=15),
        ),
        migrations.AddField(
            model_name='torneo',
            name='formato',
            field=models.CharField(choices=[('GRUPOS_SOLO', 'Solo fase de grupos (liga)'), ('GRUPOS_FINAL', 'Grupos + Final'), ('GRUPOS_SEMI', 'Grupos + Semifinales + Final'), ('GRUPOS_CUARTOS', 'Grupos + Cuartos + Semifinales + Final')], default='GRUPOS_SOLO', max_length=20),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='inscripciones.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_visita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visita', to='inscripciones.equipo'),
        ),
    ]
