# Generated by Django 5.0.6 on 2026-03-14 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('num_documento', models.CharField(max_length=12, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('ENTRENADOR', 'Entrenador'), ('JUGADOR', 'Jugador')], default='ADMIN', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.usuario')),
                ('experiencia', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.usuario',),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.usuario')),
                ('dorsal', models.PositiveIntegerField()),
                ('pie_dominante', models.CharField(max_length=20)),
                ('posicion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
            bases=('accounts.usuario',),
        ),
    ]
