# Generated by Django 5.0.6 on 2026-03-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrenador',
            options={'verbose_name': 'Entrenador', 'verbose_name_plural': 'Entrenadores'},
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='experiencia',
            field=models.CharField(db_column='experiencia', max_length=15),
        ),
        migrations.RenameField(
            model_name='entrenador',
            old_name='experiencia',
            new_name='_experiencia',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='dorsal',
            field=models.PositiveIntegerField(db_column='dorsal'),
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='dorsal',
            new_name='_dorsal',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='pie_dominante',
            field=models.CharField(db_column='pie_dominante', max_length=20),
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='pie_dominante',
            new_name='_pie_dominante',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(db_column='posicion', max_length=50),
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='posicion',
            new_name='_posicion',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(db_column='apellidos', max_length=50),
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidos',
            new_name='_apellidos',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(db_column='email', max_length=254, unique=True),
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='_email',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(db_column='fecha_nacimiento'),
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_nacimiento',
            new_name='_fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(db_column='nombres', max_length=50),
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombres',
            new_name='_nombres',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='num_documento',
            field=models.CharField(db_column='num_documento', max_length=12, unique=True),
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='num_documento',
            new_name='_num_documento',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ENTRENADOR', 'Entrenador'), ('JUGADOR', 'Jugador')], db_column='rol', default='ADMIN', max_length=15),
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='rol',
            new_name='_rol',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(db_column='telefono', max_length=20, unique=True),
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono',
            new_name='_telefono',
        ),
    ]
