# Generated by Django 5.0.6 on 2026-03-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_is_active_usuario_is_staff'),
        ('inscripciones', '0002_equipo__motivo_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='inscripciones.equipo'),
        ),
    ]
