# Generated by Django 5.0.6 on 2026-05-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jugador_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenador',
            name='_experiencia',
            field=models.PositiveIntegerField(db_column='experiencia'),
        ),
    ]
