# Generated by Django 5.0.6 on 2026-03-25 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_usuario_is_active_usuario_is_staff'),
        ('inscripciones', '0002_equipo__motivo_rechazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la sesión')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('lugar', models.CharField(max_length=150)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_entrenamientos', to='accounts.entrenador')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos', to='inscripciones.equipo')),
            ],
            options={
                'verbose_name': 'Entrenamiento',
                'verbose_name_plural': 'Entrenamientos',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
