# Generated by Codex on 2026-04-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_cancha__latitud_cancha__longitud'),
        ('entrenamientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='cancha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrenamientos_programados', to='inscripciones.cancha'),
        ),
    ]
