# Generated by Django 5.0.6 on 2026-06-22 17:43

from django.db import migrations, models
from django.utils import timezone


def completar_estado_entrenamientos(apps, schema_editor):
    Entrenamiento = apps.get_model('entrenamientos', 'Entrenamiento')
    ahora = timezone.now()
    for entrenamiento in Entrenamiento.objects.all():
        if not entrenamiento.fecha_fin:
            entrenamiento.fecha_fin = entrenamiento.fecha_hora

        if ahora < entrenamiento.fecha_hora:
            entrenamiento.estado = 'PROGRAMADO'
        elif entrenamiento.fecha_hora <= ahora <= entrenamiento.fecha_fin:
            entrenamiento.estado = 'EN_CURSO'
        else:
            entrenamiento.estado = 'FINALIZADO'

        entrenamiento.save(update_fields=['fecha_fin', 'estado'])


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0003_asistenciaentrenamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado')], default='PROGRAMADO', max_length=15),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalizacion'),
        ),
        migrations.RunPython(completar_estado_entrenamientos, migrations.RunPython.noop),
    ]
