# Generated by Django 5.0.6 on 2026-03-17 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_usuario_is_active_usuario_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_nombre', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('_descripcion', models.TextField(blank=True, db_column='descripcion')),
                ('_anio_fundacion', models.PositiveIntegerField(db_column='anio_fundacion')),
                ('_logo', models.ImageField(blank=True, db_column='logo', null=True, upload_to='equipos/logos/')),
                ('_categoria', models.CharField(choices=[('SUB8', 'Sub-8'), ('SUB10', 'Sub-10'), ('SUB12', 'Sub-12'), ('SUB14', 'Sub-14'), ('SUB16', 'Sub-16'), ('SUB18', 'Sub-18'), ('MAYOR', 'Mayor/Libre')], db_column='categoria', max_length=10)),
                ('_localidad', models.CharField(db_column='localidad', max_length=100)),
                ('_barrio', models.CharField(db_column='barrio', max_length=100)),
                ('_estado', models.CharField(choices=[('ESPERA', 'En espera'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], db_column='estado', default='ESPERA', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('entrenador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='accounts.entrenador')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
