# Generated by Django 5.0.6 on 2026-03-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='_motivo_rechazo',
            field=models.TextField(blank=True, db_column='motivo_rechazo', null=True),
        ),
    ]
