# Generated by Django 5.0.6 on 2026-03-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_equipo__motivo_rechazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_codigo_idrd', models.CharField(blank=True, db_column='codigo_idrd', max_length=50, null=True)),
                ('_nombre_escenario', models.CharField(db_column='nombre_escenario', max_length=150)),
                ('_localidad', models.CharField(db_column='localidad', max_length=100)),
                ('_barrio', models.CharField(db_column='barrio', max_length=100)),
                ('_direccion_exacta', models.CharField(db_column='direccion_exacta', max_length=200)),
                ('_codigo_rupi', models.CharField(blank=True, db_column='codigo_rupi', max_length=50, null=True)),
                ('_tipo_disciplina', models.CharField(choices=[('FUTBOL_11', 'Futbol 11'), ('FUTBOL_8', 'Futbol 8'), ('FUTBOL_5', 'Futbol 5'), ('MICROFUTBOL', 'Microfútbol')], db_column='tipo_disciplina', max_length=20)),
                ('_tipo_superficie', models.CharField(choices=[('SINTETICA', 'Sintetica'), ('NATURAL', 'Natural'), ('ARENA', 'Arena'), ('CEMENTO', 'Cemento (Dura)')], db_column='tipo_superficie', max_length=20)),
                ('_medidas_area', models.CharField(db_column='medidas_area', max_length=50)),
                ('_estado_conservacion', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('CRITICO', 'Critico')], db_column='estado_conservacion', max_length=10)),
                ('_tiene_iluminacion', models.BooleanField(db_column='tiene_iluminacion', default=False)),
                ('_tiene_cerramiento', models.BooleanField(db_column='tiene_cerramiento', default=False)),
                ('_capacidad_espectadores', models.PositiveIntegerField(db_column='capacidad_espectadores', default=0)),
                ('_observaciones_tecnicas', models.TextField(blank=True, db_column='observaciones_tecnicas', null=True)),
                ('_disponibilidad', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('MANTENIMIENTO', 'En Mantenimiento'), ('FUERA_SERVICIO', 'Fuera de servicio')], db_column='disponibilidad', default='DISPONIBLE', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'ordering': ['_nombre_escenario'],
            },
        ),
    ]
