# Generated by Django 5.0.6 on 2026-04-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_cancha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='_latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='_longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
