# Generated by Django 5.0.6 on 2026-05-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_cancha__latitud_cancha__longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='_bloqueado_hasta',
            field=models.DateTimeField(blank=True, db_column='bloqueado_hasta', null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='_eliminar_programada_para',
            field=models.DateTimeField(blank=True, db_column='eliminar_programada_para', null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='_fecha_rechazo',
            field=models.DateTimeField(blank=True, db_column='fecha_rechazo', null=True),
        ),
    ]
