# Generated by Django 5.0.6 on 2026-05-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0005_equipo__bloqueado_hasta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='_motivo_eliminacion',
            field=models.TextField(blank=True, db_column='motivo_eliminacion', null=True),
        ),
    ]
