# Generated by Django 5.0.6 on 2026-06-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_entrenador__experiencia'),
        ('inscripciones', '0009_remove_equipo_nombre_unico'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.UniqueConstraint(fields=('entrenador', '_categoria'), name='unique_entrenador_categoria', violation_error_message='El entrenador ya tiene un equipo registrado en esta categoría.'),
        ),
    ]
